// Generated by gencpp from file robot_controller/Floats_array.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROLLER_MESSAGE_FLOATS_ARRAY_H
#define ROBOT_CONTROLLER_MESSAGE_FLOATS_ARRAY_H

#include <ros/service_traits.h>


#include <robot_controller/Floats_arrayRequest.h>
#include <robot_controller/Floats_arrayResponse.h>


namespace robot_controller
{

struct Floats_array
{

typedef Floats_arrayRequest Request;
typedef Floats_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Floats_array
} // namespace robot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_controller::Floats_array > {
  static const char* value()
  {
    return "086e0a6631d243c06d9ccfa024bfe376";
  }

  static const char* value(const ::robot_controller::Floats_array&) { return value(); }
};

template<>
struct DataType< ::robot_controller::Floats_array > {
  static const char* value()
  {
    return "robot_controller/Floats_array";
  }

  static const char* value(const ::robot_controller::Floats_array&) { return value(); }
};


// service_traits::MD5Sum< ::robot_controller::Floats_arrayRequest> should match
// service_traits::MD5Sum< ::robot_controller::Floats_array >
template<>
struct MD5Sum< ::robot_controller::Floats_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_controller::Floats_array >::value();
  }
  static const char* value(const ::robot_controller::Floats_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_controller::Floats_arrayRequest> should match
// service_traits::DataType< ::robot_controller::Floats_array >
template<>
struct DataType< ::robot_controller::Floats_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::robot_controller::Floats_array >::value();
  }
  static const char* value(const ::robot_controller::Floats_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_controller::Floats_arrayResponse> should match
// service_traits::MD5Sum< ::robot_controller::Floats_array >
template<>
struct MD5Sum< ::robot_controller::Floats_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_controller::Floats_array >::value();
  }
  static const char* value(const ::robot_controller::Floats_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_controller::Floats_arrayResponse> should match
// service_traits::DataType< ::robot_controller::Floats_array >
template<>
struct DataType< ::robot_controller::Floats_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::robot_controller::Floats_array >::value();
  }
  static const char* value(const ::robot_controller::Floats_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_CONTROLLER_MESSAGE_FLOATS_ARRAY_H
